### ISSUE TITLE
域名必须要注册吗,还是注册之后更安全

### ISSUE THREAD

**Issue by jiachunxu** [docmirror/dev-sidecar-doc#2]
### 没有域名,直接用填IP地址行吗,还是必须注册一个
![image](https://user-images.githubusercontent.com/37132291/130357036-22553f49-a68b-444b-9f81-4a8ffe4343af.png)

**Comment by greper** [comment]
你可以用IP地址试试

**Comment by jiachunxu** [comment]
@

**Comment by jiachunxu** [comment]
怕不成,提前问一下😂

**Comment by greper** [comment]
证书是必须要的

**Comment by jiachunxu** [comment]
ok
![image](https://user-images.githubusercontent.com/37132291/130357460-9885a3b6-6a10-4430-ae82-ae79080451d2.png)
这两个吧

**Comment by greper** [comment]
不是，是nginx开启tls的证书，没有域名你可以搞个自签名证书

**Comment by jiachunxu** [comment]
我还是再学学吧,先不折腾了🤣
